# Generated by Django 2.2.6 on 2019-10-26 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alignment',
            name='status',
            field=models.CharField(choices=[('Processed', 'Processed'), ('New', 'New')], default='New', max_length=10),
        ),
        migrations.AlterField(
            model_name='alignment',
            name='alignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alignments.Protein'),
        ),
    ]
