# Generated by Django 2.2.6 on 2019-10-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignments', '0002_auto_20191026_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protein',
            old_name='name',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='ref',
        ),
        migrations.AddField(
            model_name='protein',
            name='reference',
            field=models.CharField(default='0', max_length=16),
            preserve_default=False,
        ),
    ]
