# Generated by Django 2.2.6 on 2019-10-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignments', '0003_auto_20191030_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alignment',
            name='alignment',
        ),
        migrations.AddField(
            model_name='alignment',
            name='result_name',
            field=models.CharField(default='default', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alignment',
            name='result_start',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
