# Generated by Django 2.2.6 on 2019-10-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignments', '0004_auto_20191030_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alignment',
            name='result_name',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='alignment',
            name='result_start',
            field=models.IntegerField(blank=True),
        ),
    ]
