# Generated by Django 2.2.6 on 2019-10-31 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignments', '0005_auto_20191030_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alignment',
            name='result_name',
            field=models.CharField(default='No Match', max_length=16),
        ),
        migrations.AlterField(
            model_name='alignment',
            name='result_start',
            field=models.IntegerField(default=-1),
        ),
    ]
