# Generated by Django 2.2.6 on 2019-10-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignments', '0008_auto_20191031_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='sequence',
            field=models.TextField(blank=True, null=True),
        ),
    ]
