# Generated by Django 2.2.6 on 2019-10-31 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignments', '0009_auto_20191031_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='file',
            field=models.FileField(upload_to='alignments/static/files/protein_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['fasta'])]),
        ),
    ]
